#!/usr/bin/env python3
"""Render a release-local install verification guide from packaged manifests."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ASSET_MANIFEST_FIELDS = {
    "archive",
    "archive_sha256",
    "binary",
    "tag",
    "target",
}


def load_asset_manifests(artifacts_dir: Path) -> list[dict[str, Any]]:
    """Load per-asset manifests while ignoring aggregate provenance summaries."""
    manifests: list[dict[str, Any]] = []
    for path in sorted(artifacts_dir.glob("*.json")):
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise SystemExit(f"JSON evidence is not an object: {path.name}")
        present = ASSET_MANIFEST_FIELDS.intersection(value)
        if not present:
            continue
        missing = ASSET_MANIFEST_FIELDS.difference(value)
        if missing:
            raise SystemExit(
                f"Incomplete asset manifest {path.name}: missing {sorted(missing)}"
            )
        manifests.append(value)
    return manifests


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--artifacts-dir", type=Path, required=True)
    parser.add_argument("--expected-tag", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    manifests = load_asset_manifests(args.artifacts_dir)
    if not manifests:
        raise SystemExit("No asset manifest files found")

    for manifest in manifests:
        if manifest.get("tag") != args.expected_tag:
            raise SystemExit(f"Unexpected tag in manifest: {manifest.get('archive')}")

    lines = [
        f"# Install and verification guide ({args.expected_tag})",
        "",
        "This file is generated by CI from the published release manifests.",
        "",
        "## Verify downloads",
        "",
        "```bash",
        "sha256sum -c SHA256SUMS.txt --ignore-missing",
        "```",
        "",
        "## Per-target quick checks",
        "",
    ]

    for manifest in sorted(manifests, key=lambda item: (item["target"], item["binary"])):
        archive = manifest["archive"]
        target = manifest["target"]
        binary = manifest["binary"]
        base = archive.removesuffix(".tar.gz").removesuffix(".zip")
        command = f"./{base}/{binary} --version"
        if binary.startswith("pulsedag-miner"):
            command = f"./{base}/{binary} --help"

        lines.extend(
            [
                f"### {target}: {binary}",
                "",
                f"- Archive: `{archive}`",
                f"- SHA256: `{manifest['archive_sha256']}`",
                "",
                "```bash",
                f"# unpack {archive}",
                command,
                "```",
                "",
            ]
        )

    args.output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
