[package]
name = "pulsedag-p2p"
version.workspace = true
edition = "2021"

[dependencies]
pulsedag-core = { path = "../pulsedag-core" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
tokio = { version = "1", features = ["sync", "rt", "macros", "time"] }
libp2p = { version = "0.56.0", default-features = false, features = ["tokio", "gossipsub", "identify", "kad", "macros", "tcp", "noise", "yamux", "ping"] }

[dev-dependencies]
tempfile = "3"
